// This file is automatically generated from your CSS. Any edits will be overwritten.
export const panel: string;
export const panelNoMargin: string;
export const flex: string;
export const flexColumn: string;
export const widthFull: string;
export const widthHalf: string;
